### ISSUE TITLE
Operator does not support more than 1 SAN

### ISSUE THREAD

**Issue by bjpritch** [patrickeasters/ipa-cert-operator#6]
Either by design or bug, the current version of the operator does not support multiple SANs attached to a certificate. To replicate:

1. Create an IpaCert object with multiple SANs in "AdditionalNames" field:

```
kind: IpaCert
apiVersion: cert.patrickeasters.com/v1alpha1
metadata:
  name: mongo-cert
spec:
  cn: mongo1.apps.example.com
  type: host
  AdditionalNames:
  - mongo1.apps.example.com
  - mongo2.apps.example.com
  - mongo3.apps.example.com
  - mongo
  - mongo.benstest
  - mongo.benstest.svc.cluster.local
```
2. Review the generated certificate, and notice only 1 SAN attached:
```
$ cat test.crt | base64 --decode | openssl x509 -noout -text | grep -A 2 Alternative
            X509v3 Subject Alternative Name: 
                DNS:mongo1.apps.example.com
    Signature Algorithm: sha256WithRSAEncryption
```

I'd expect that any SANs put into the IpaCert object would appropriately get attached to the generated certificate.
